Multiple small fixes to keep code up to date plus improvements (#2)
* Add RiskMaster related apps

* Add AMI lookup lambda function for Amazon NAT

* add stackset cross-account role

* add CoreCustomAMIFunctions, to lookup CIS and OpenVPN Marketplace AMIs

* add Examples to test CoreCustomAMIFunctions

* Move build-related files under new section

* convert default access to private, add backups bucket

* Update OpenVPN AS version to 2.1.9 in ImageIdMap

* adjust sequence script order and split out build

* Update CustomUsers to recent group membership changes

* Add additional Review Users

* Update Identity VPC to support NAT Instances

* set the default value for an administration account

* add TemplatesBucketPolicy to allow CloudFormation to read templates

* Update Core VPC to support NAT Instances

* Update Build VPC to support NAT Instances

* Add missing local Stack Override policy to build section

* Update Environment VPC to support NAT Instances

* Added ASchickUser, late addition to HLS team

* adjust validation logic to longer subnet id

* update references to Windows AMIs to latest versions

* change MCrawford home IP from static range to single dynamic

* back out S3Endpoint accidentally checked in

* small fixes for consistency to get this running again

* update AMI to latest version; change on/off schedule

* update StandardAMI lookup functions to recent versions

* Update OpenVPNAS to use 2.5.0 AMIs

* Update Lambda to lookup OpenVPNAS to support 100-user license

* fix missing execute permission

* minor updates to LinuxBastions

* Update Windows AMI versions

* add EIP to DNS name preserved across stop/start; update to RHEL 7.5

* small updates to Example-LinuxWebServers

* small updates to Example-NestedLinuxWebServer

* small updates to Example-NestedLinuxWebServers

* small updates to Example-WindowsWebServer

* Add OpenVPNAS Version; Switch from ImageId Mapping Table to Lambda AMI Lookup

* small updates to Octopus-Deploy

* updated Windows AMI versions

diff --git a/build/bin/build-update-vpc-stack b/build/bin/build-update-vpc-stack
--- a/build/bin/build-update-vpc-stack
+++ b/build/bin/build-update-vpc-stack
@@ -1,6 +1,6 @@
 #!/bin/bash
 #
-# This script creates the Build VPC Stack in the Core Account.
+# This script updates the Build VPC Stack in the Core Account.
 #
 
 #  1. Initalize Environment
@@ -14,17 +14,20 @@ speed_max=400
 run_default=10
 pause_default=2
 next_default=5
-create_default=15
-create_attempts=40
+update_default=15
+update_attempts=40
 
 interactive=0
 speed=100
 verbose=0
 monitor=0
+override=0
 owner=${OWNER_EMAIL:-$USER@dxc.com}
 company=${COMPANY_NAME:-DXC}
 system=${SYSTEM_NAME:-Prototype}
 environment=${BUILD_NAME:-Build}
+environment_type=${ENVIRONMENT_TYPE:-nano}
+environment_zones=${ENVIRONMENT_ZONES:-1}
 environment_network=${BUILD_NETWORK:-172.21.60.0/23}
 environment_public_domain=${BUILD_PUBLIC_DOMAIN:-b.us-west-2.dxcp.technology}
 environment_private_domain=${BUILD_PRIVATE_DOMAIN:-b.dxcp.technology}
@@ -32,25 +35,29 @@ environment_netbios_domain=${BUILD_NETBIOS_DOMAIN:-dxcpb}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-dxcp}
 user=${AWS_USER_NAME:-administrator}
+key=${AWS_KEY_NAME:-administrator}
 
 
 #  2. Define functions
 
 usage () {
-    echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-m]"
+    echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-m] [-o]"
     echo "                  [-O owner] [-C company] [-S system]"
-    echo "                  [-E environment] [-N network]"
+    echo "                  [-E environment] [-T type] [-Z zones] [-N network]"
     echo "                  [-D domain] [-d domain] [-b domain]"
-    echo "                  [-r region] [-a account] [-u user]"
+    echo "                  [-r region] [-a account] [-u user] [-k key]"
     echo "  -i              interactive"
     echo "  -s              slower: increase pauses by 25%"
     echo "  -f              faster: reduce pauses by 25%"
     echo "  -v              verbose"
     echo "  -m              monitor"
+    echo "  -o              override StackPolicy"
     echo "  -O owner        Owner Email (default: $owner)"
     echo "  -C company      Company Name (default: $company)"
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
+    echo "  -T type         Environment Type (default: $environment_type)"
+    echo "  -Z zones        Environment Zones (default: $environment_zones)"
     echo "  -N network      Environment Network (default: $environment_network)"
     echo "  -D domain       Environment Public Domain (default: $environment_public_domain)"
     echo "  -d domain       Environment Private Domain (default: $environment_private_domain)"
@@ -58,6 +65,7 @@ usage () {
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
+    echo "  -k key          Key (default: $key)"
 }
 
 run() {
@@ -140,17 +148,20 @@ next() {
 
 #  3. Parse command line options
 
-while getopts isfvmO:C:S:E:N:D:d:b:r:a:u:? arg; do
+while getopts isfvmoO:C:S:E:T:Z:N:D:d:b:r:a:u:k:? arg; do
     case $arg in
     i)  interactive=1;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
     f)  ((speed > 0)) && ((speed=speed-25));;
     v)  verbose=1;;
     m)  monitor=1;;
+    o)  override=1;;
     O)  owner="$OPTARG";;
     C)  company="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
+    T)  environment_type="$OPTARG";;
+    Z)  environment_zones="$OPTARG";;
     N)  environment_network="$OPTARG";;
     D)  environment_public_domain="$OPTARG";;
     d)  environment_private_domain="$OPTARG";;
@@ -158,6 +169,7 @@ while getopts isfvmO:C:S:E:N:D:d:b:r:a:u:? arg; do
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
+    k)  key="$OPTARG";;
     ?)  usage
         exit 1;;
     esac
@@ -215,7 +227,6 @@ else
         availability_zones_per_vpc=2
         use_public_hostedzone=true
         use_private_hostedzone=false
-        use_multi_zone_nat_gateways=false
         use_vpn_gateway=true;;
       *)
         echo "-E $environment invalid! Must be Build"
@@ -223,28 +234,60 @@ else
     esac
 fi
 
+if [ -z $environment_type ]; then
+    echo "-T type missing!"
+    echo "Could not automatically determine environment type, and it was not specified as a parameter"
+    exit 22
+else
+    case $environment_type in
+      nano|micro|small|medium)
+        use_nat_gateway=false
+        ;;
+      large|xlarge)
+        use_nat_gateway=true
+        ;;
+      *)
+        echo "-T $environment_type invalid! Must be nano, micro, small, medium, large or xlarge"
+        exit 23;;
+    esac
+fi
+
+if [ -z $environment_zones ]; then
+    echo "-Z zones missing!"
+    echo "Could not automatically determine environment zones, and it was not specified as a parameter"
+    exit 24
+else
+    case $environment_zones in
+      1|2)
+        ;;
+      *)
+        echo "-Z $environment_zones invalid! Must be 1 or 2"
+        exit 25;;
+    esac
+fi
+
 if [ -z $environment_network ]; then
     echo "-N network missing!"
     echo "Could not automatically determine environment network, and it was not specified as a parameter"
-    exit 22
+    exit 26
 fi
 
 if [ -z $environment_public_domain ]; then
     echo "-D domain missing!"
     echo "Could not automatically determine public domain, and it was not specified as a parameter"
-    exit 24
+    exit 120
 fi
 
 if [ -z $environment_private_domain ]; then
     echo "-d domain missing!"
     echo "Could not automatically determine private domain, and it was not specified as a parameter"
-    exit 26
+    exit 122
 fi
 
 if [ -z $environment_netbios_domain ]; then
     echo "-b domain missing!"
     echo "Could not automatically determine NetBIOS domain, and it was not specified as a parameter"
-    exit 28
+    exit 124
 fi
 
 if [ -z $region ]; then
@@ -275,6 +318,12 @@ if [ -z $user ]; then
     exit 54
 fi
 
+if [ -z $key ]; then
+    echo "-k key missing!"
+    echo "Could not automatically determine key, and it was not specified as a parameter"
+    exit 56
+fi
+
 profile=$account-$user
 
 if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
@@ -283,8 +332,21 @@ if ! grep -s -q "\[profile $profile]" ~/.aws/config; then
     exit 58
 fi
 
+echo -n "Confirming Stack pre-requisites "
+
+if ! aws cloudformation describe-stacks --stack-name $environment-VPC \
+                                        --profile $profile --region $region --output text &> /dev/null; then
+    echo
+    echo "Unable to update - $environment-VPC Stack does not exist!"
+    exit 98
+else
+    echo -n "."
+fi
+echo " Done"
+sleep 1
+
 templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
-template_folder=core
+template_folder=build
 
 if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --region $region 2> /dev/null; then
     unset templates_bucket
@@ -375,11 +437,21 @@ else
     template_parameter="--template-body file://$templatesdir/Build-VPC.json"
     stack_policy_parameter="--stack-policy-body file://$templatesdir/Build-VPC-StackPolicy.json"
 fi
+if [ $override = 1 ]; then
+    stack_policy_parameter="$stack_policy_parameter \\"$'\n'"                                --stack-policy-during-update-body file://$templatesdir/Override-StackPolicy.json"
+fi
 read -r -d '' statement << EOS
-aws cloudformation create-stack --stack-name $environment-VPC \\
+aws cloudformation update-stack --stack-name $environment-VPC \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
-                                --parameters ParameterKey=Name,ParameterValue=$environment \\
+                                --parameters ParameterKey=StandardCIDRFunctionsStackName,ParameterValue=StandardCIDRFunctions \\
+                                             ParameterKey=StandardAMIFunctionsStackName,ParameterValue=StandardAMIFunctions \\
+                                             ParameterKey=KeyName,ParameterValue=$key \\
+                                             ParameterKey=CompanyName,ParameterValue=$company \\
+                                             ParameterKey=SystemName,ParameterValue=$system \\
+                                             ParameterKey=EnvironmentType,ParameterValue=$environment_type \\
+                                             ParameterKey=EnvironmentZones,ParameterValue=$environment_zones \\
+                                             ParameterKey=Name,ParameterValue=$environment \\
                                              ParameterKey=Network,ParameterValue=$environment_network \\
                                              ParameterKey=AddressesPerSubnet,ParameterValue=$addresses_per_subnet \\
                                              ParameterKey=SubnetsPerAvailabilityZone,ParameterValue=$subnets_per_availability_zone \\
@@ -389,7 +461,7 @@ aws cloudformation create-stack --stack-name $environment-VPC \\
                                              ParameterKey=NetBIOSDomain,ParameterValue=$environment_netbios_domain \\
                                              ParameterKey=UsePublicHostedZone,ParameterValue=$use_public_hostedzone \\
                                              ParameterKey=UsePrivateHostedZone,ParameterValue=$use_private_hostedzone \\
-                                             ParameterKey=UseMultiZoneNatGateways,ParameterValue=$use_multi_zone_nat_gateways \\
+                                             ParameterKey=UseNatGateway,ParameterValue=$use_nat_gateway \\
                                              ParameterKey=UseVPNGateway,ParameterValue=$use_vpn_gateway \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
@@ -405,7 +477,7 @@ clear
 echo
 echo "============================================================"
 echo
-echo "$(printf '%2d' $step). Create the Stack"
+echo "$(printf '%2d' $step). Update the Stack"
 echo
 echo "============================================================"
 echo
@@ -413,25 +485,14 @@ echo "Commands:"
 echo
 echo "$statement"
 
-if aws cloudformation describe-stacks --stack-name $environment-VPC \
-                                      --profile $profile --region $region --output text &> /dev/null; then
+run
+
+if [ $choice = y ]; then
     echo
-    tput rev
-    echo "Already Created!"
-    tput sgr0
+    echo "$run_statement"
+    eval "$eval_statement"
 
-    next 50
-
-else
-    run
-
-    if [ $choice = y ]; then
-        echo
-        echo "$run_statement"
-        eval "$eval_statement"
-
-        next
-    fi
+    next
 fi
 
 
@@ -457,7 +518,7 @@ if [ $monitor = 1 ]; then
     echo
     echo "============================================================"
     echo
-    echo "$(printf '%2d' $step). Monitor Stack creation"
+    echo "$(printf '%2d' $step). Monitor Stack update"
     echo
     echo "============================================================"
     echo
@@ -469,7 +530,7 @@ if [ $monitor = 1 ]; then
 
     if [ "$(aws cloudformation describe-stacks --stack-name $environment-VPC \
                                                --query 'Stacks[].StackStatus' \
-                                               --profile $profile --region $region --output text 2> /dev/null)" = "CREATE_COMPLETE" ]; then
+                                               --profile $profile --region $region --output text 2> /dev/null)" = "UPDATE_COMPLETE" ]; then
         echo
         tput rev
         echo "Already Complete!"
@@ -486,8 +547,8 @@ if [ $monitor = 1 ]; then
             eval "$eval_statement"
 
             attempt=0
-            seconds=$create_default
-            while ((attempt++ <= create_attempts)); do
+            seconds=$update_default
+            while ((attempt++ <= update_attempts)); do
                 echo
                 echo "$run_statement2"
                 eval "$eval_statement2"
@@ -495,7 +556,7 @@ if [ $monitor = 1 ]; then
                 status=$(aws cloudformation describe-stacks --stack-name $environment-VPC \
                                                             --query 'Stacks[].StackStatus' \
                                                             --profile $profile --region $region --output text 2> /dev/null)
-                if [ -z "$status" -o "$status" = "CREATE_COMPLETE" -o "$status" = "CREATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
+                if [ -z "$status" -o "$status" = "UPDATE_COMPLETE" -o "$status" = "UPDATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
                     break
                 else
                     echo
diff --git a/core/bin/core-update-customamifunctions-stack b/core/bin/core-update-customamifunctions-stack
--- a/core/bin/core-update-customamifunctions-stack
+++ b/core/bin/core-update-customamifunctions-stack
@@ -1,12 +1,13 @@
 #!/bin/bash
 #
-# This script updates the Build VPC Stack in the Core Account.
+# This script updates the CustomAMIFunctions Stack in the Core Account.
 #
 
 #  1. Initalize Environment
 
 bindir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
 templatesdir=${bindir%/*}/templates
+functionsdir=${bindir%/*}/functions
 tmpdir=/var/tmp
 
 step=0
@@ -25,11 +26,7 @@ override=0
 owner=${OWNER_EMAIL:-$USER@dxc.com}
 company=${COMPANY_NAME:-DXC}
 system=${SYSTEM_NAME:-Prototype}
-environment=${BUILD_NAME:-Build}
-environment_network=${BUILD_NETWORK:-172.21.60.0/23}
-environment_public_domain=${BUILD_PUBLIC_DOMAIN:-b.us-west-2.dxcp.technology}
-environment_private_domain=${BUILD_PRIVATE_DOMAIN:-b.dxcp.technology}
-environment_netbios_domain=${BUILD_NETBIOS_DOMAIN:-dxcpb}
+environment=${CORE_NAME:-Core}
 region=${AWS_DEFAULT_REGION:-us-west-2}
 account=${AWS_ACCOUNT_ALIAS:-dxcp}
 user=${AWS_USER_NAME:-administrator}
@@ -40,8 +37,7 @@ user=${AWS_USER_NAME:-administrator}
 usage () {
     echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-m] [-o]"
     echo "                  [-O owner] [-C company] [-S system]"
-    echo "                  [-E environment] [-N network]"
-    echo "                  [-D domain] [-d domain] [-b domain]"
+    echo "                  [-E environment]"
     echo "                  [-r region] [-a account] [-u user]"
     echo "  -i              interactive"
     echo "  -s              slower: increase pauses by 25%"
@@ -53,10 +49,6 @@ usage () {
     echo "  -C company      Company Name (default: $company)"
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
-    echo "  -N network      Environment Network (default: $environment_network)"
-    echo "  -D domain       Environment Public Domain (default: $environment_public_domain)"
-    echo "  -d domain       Environment Private Domain (default: $environment_private_domain)"
-    echo "  -b domain       Environment NetBIOS Domain (default: $environment_netbios_domain)"
     echo "  -r region       Region (default: $region)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
@@ -142,7 +134,7 @@ next() {
 
 #  3. Parse command line options
 
-while getopts isfvmoO:C:S:E:N:D:d:b:r:a:u:? arg; do
+while getopts isfvmoO:C:S:E:r:a:u:? arg; do
     case $arg in
     i)  interactive=1;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
@@ -154,10 +146,6 @@ while getopts isfvmoO:C:S:E:N:D:d:b:r:a:u:? arg; do
     C)  company="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
-    N)  environment_network="$OPTARG";;
-    D)  environment_public_domain="$OPTARG";;
-    d)  environment_private_domain="$OPTARG";;
-    b)  environment_netbios_domain="$OPTARG";;
     r)  region="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
@@ -212,42 +200,12 @@ if [ -z $environment ]; then
     exit 20
 else
     case $environment in
-      Build)
-        addresses_per_subnet=16
-        subnets_per_availability_zone=16
-        availability_zones_per_vpc=2
-        use_public_hostedzone=true
-        use_private_hostedzone=false
-        use_multi_zone_nat_gateways=false
-        use_vpn_gateway=true;;
+      Core)
+        ;;
       *)
-        echo "-E $environment invalid! Must be Build"
+        echo "-E $environment invalid! Must be Core"
         exit 21;;
     esac
-fi
-
-if [ -z $environment_network ]; then
-    echo "-N network missing!"
-    echo "Could not automatically determine environment network, and it was not specified as a parameter"
-    exit 22
-fi
-
-if [ -z $environment_public_domain ]; then
-    echo "-D domain missing!"
-    echo "Could not automatically determine public domain, and it was not specified as a parameter"
-    exit 24
-fi
-
-if [ -z $environment_private_domain ]; then
-    echo "-d domain missing!"
-    echo "Could not automatically determine private domain, and it was not specified as a parameter"
-    exit 26
-fi
-
-if [ -z $environment_netbios_domain ]; then
-    echo "-b domain missing!"
-    echo "Could not automatically determine NetBIOS domain, and it was not specified as a parameter"
-    exit 28
 fi
 
 if [ -z $region ]; then
@@ -288,10 +246,10 @@ fi
 
 echo -n "Confirming Stack pre-requisites "
 
-if ! aws cloudformation describe-stacks --stack-name $environment-VPC \
+if ! aws cloudformation describe-stacks --stack-name CustomAMIFunctions \
                                         --profile $profile --region $region --output text &> /dev/null; then
     echo
-    echo "Unable to update - $environment-VPC Stack does not exist!"
+    echo "Unable to update - CustomAMIFunctions Stack does not exist!"
     exit 98
 else
     echo -n "."
@@ -301,10 +259,6 @@ sleep 1
 
 templates_bucket=${AWS_TEMPLATES_BUCKET:-templates-$region-$account}
 template_folder=core
-
-if ! aws s3api head-bucket --bucket $templates_bucket --profile $profile --region $region 2> /dev/null; then
-    unset templates_bucket
-fi
 
 # Prevent certain environment variables from breaking commands
 unset AWS_DEFAULT_PROFILE
@@ -354,62 +308,43 @@ fi
 read -r -d '' statement << EOS
 aws s3 sync $templatesdir \\
             s3://$templates_bucket/$template_folder \\
-            --exclude '*' --include 'Build-VPC.json' --include 'Build-VPC-StackPolicy.json' \\
+            --exclude '*' --include 'Core-CustomAMIFunctions.json' --include 'Core-CustomAMIFunctions-StackPolicy.json' \\
             --profile $profile --region $region --output table
 EOS
 run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'}"
 
-if [ ! -z $templates_bucket ]; then
-    clear
-    echo
-    echo "============================================================"
-    echo
-    echo "$(printf '%2d' $step). Sync Template and Policy to ($templates_bucket) Bucket"
-    echo
-    echo "============================================================"
-    echo
-    echo "Commands:"
-    echo
-    echo "$statement"
+clear
+echo
+echo "============================================================"
+echo
+echo "$(printf '%2d' $step). Sync Template and Policy to ($templates_bucket) Bucket"
+echo
+echo "============================================================"
+echo
+echo "Commands:"
+echo
+echo "$statement"
 
-    next 50
+next 50
 
-    echo
-    echo "$run_statement"
-    eval "$eval_statement"
+echo
+echo "$run_statement"
+eval "$eval_statement"
 
-    next 50
-fi
+next 50
 
 
 ((++step))
-if [ ! -z $templates_bucket ]; then
-    template_parameter="--template-url https://$s3_domain/$templates_bucket/$template_folder/Build-VPC.json"
-    stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$template_folder/Build-VPC-StackPolicy.json"
-else
-    template_parameter="--template-body file://$templatesdir/Build-VPC.json"
-    stack_policy_parameter="--stack-policy-body file://$templatesdir/Build-VPC-StackPolicy.json"
-fi
+template_parameter="--template-url https://$s3_domain/$templates_bucket/$template_folder/Core-CustomAMIFunctions.json"
+stack_policy_parameter="--stack-policy-url https://$s3_domain/$templates_bucket/$template_folder/Core-CustomAMIFunctions-StackPolicy.json"
 if [ $override = 1 ]; then
     stack_policy_parameter="$stack_policy_parameter \\"$'\n'"                                --stack-policy-during-update-body file://$templatesdir/Override-StackPolicy.json"
 fi
 read -r -d '' statement << EOS
-aws cloudformation update-stack --stack-name $environment-VPC \\
+aws cloudformation update-stack --stack-name CustomAMIFunctions \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
-                                --parameters ParameterKey=Name,ParameterValue=$environment \\
-                                             ParameterKey=Network,ParameterValue=$environment_network \\
-                                             ParameterKey=AddressesPerSubnet,ParameterValue=$addresses_per_subnet \\
-                                             ParameterKey=SubnetsPerAvailabilityZone,ParameterValue=$subnets_per_availability_zone \\
-                                             ParameterKey=AvailabilityZonesPerVPC,ParameterValue=$availability_zones_per_vpc \\
-                                             ParameterKey=PublicDomain,ParameterValue=$environment_public_domain \\
-                                             ParameterKey=PrivateDomain,ParameterValue=$environment_private_domain \\
-                                             ParameterKey=NetBIOSDomain,ParameterValue=$environment_netbios_domain \\
-                                             ParameterKey=UsePublicHostedZone,ParameterValue=$use_public_hostedzone \\
-                                             ParameterKey=UsePrivateHostedZone,ParameterValue=$use_private_hostedzone \\
-                                             ParameterKey=UseMultiZoneNatGateways,ParameterValue=$use_multi_zone_nat_gateways \\
-                                             ParameterKey=UseVPNGateway,ParameterValue=$use_vpn_gateway \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
@@ -445,7 +380,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stacks --stack-name $environment-VPC \\
+aws cloudformation describe-stacks --stack-name CustomAMIFunctions \\
                                    --query 'Stacks[].[StackName,StackStatus]' \\
                                    --profile $profile --region $region --output table
 EOS
@@ -453,7 +388,7 @@ run_statement=$(echo "$statement" | sed -e '1s/^/# /;2,$ s/^/> /')
 eval_statement="${statement//\\$'\n'} 2> /dev/null"
 
 read -r -d '' statement2 << EOS
-aws cloudformation describe-stack-events --stack-name $environment-VPC --max-items 5 \\
+aws cloudformation describe-stack-events --stack-name CustomAMIFunctions --max-items 5 \\
                                          --query 'StackEvents[].[LogicalResourceId,ResourceStatus,Timestamp]' \\
                                          --profile $profile --region $region --output table
 EOS
@@ -475,7 +410,7 @@ if [ $monitor = 1 ]; then
     echo
     echo "$statement2"
 
-    if [ "$(aws cloudformation describe-stacks --stack-name $environment-VPC \
+    if [ "$(aws cloudformation describe-stacks --stack-name CustomAMIFunctions \
                                                --query 'Stacks[].StackStatus' \
                                                --profile $profile --region $region --output text 2> /dev/null)" = "UPDATE_COMPLETE" ]; then
         echo
@@ -500,7 +435,7 @@ if [ $monitor = 1 ]; then
                 echo "$run_statement2"
                 eval "$eval_statement2"
 
-                status=$(aws cloudformation describe-stacks --stack-name $environment-VPC \
+                status=$(aws cloudformation describe-stacks --stack-name CustomAMIFunctions \
                                                             --query 'Stacks[].StackStatus' \
                                                             --profile $profile --region $region --output text 2> /dev/null)
                 if [ -z "$status" -o "$status" = "UPDATE_COMPLETE" -o "$status" = "UPDATE_FAILED" -o "$status" = "ROLLBACK_COMPLETE" ]; then
@@ -554,7 +489,7 @@ fi
 
 ((++step))
 read -r -d '' statement << EOS
-aws cloudformation describe-stack-resources --stack-name $environment-VPC \\
+aws cloudformation describe-stack-resources --stack-name CustomAMIFunctions \\
                                             --query 'StackResources[].[ResourceType,LogicalResourceId,PhysicalResourceId,ResourceStatus]' \\
                                             --profile $profile --region $region --output table
 EOS
diff --git a/identity/bin/identity-create-standardroles-stack b/identity/bin/identity-create-standardroles-stack
--- a/identity/bin/identity-create-standardroles-stack
+++ b/identity/bin/identity-create-standardroles-stack
@@ -25,6 +25,7 @@ owner=${OWNER_EMAIL:-$USER@dxc.com}
 company=${COMPANY_NAME:-DXC}
 system=${SYSTEM_NAME:-Prototype}
 environment=${IDENTITY_NAME:-Identity}
+administrator_account_id=${ADMINISTRATOR_ACCOUNT_ID:-197109511535}
 region=us-east-1 # This should run only in us-east-1
 account=${AWS_ACCOUNT_ALIAS:-dxcp}
 user=${AWS_USER_NAME:-administrator}
@@ -36,6 +37,7 @@ usage () {
     echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-m]"
     echo "                  [-O owner] [-C company] [-S system]"
     echo "                  [-E environment]"
+    echo "                  [-A administrator_account_id]"
     echo "                  [-a account] [-u user]"
     echo "  -i              interactive"
     echo "  -s              slower: increase pauses by 25%"
@@ -46,6 +48,8 @@ usage () {
     echo "  -C company      Company Name (default: $company)"
     echo "  -S system       System Name (default: $system)"
     echo "  -E environment  Environment Name (default: $environment)"
+    echo "  -A administrator_account_id"
+    echo "                  Administrator Account ID (default: $administrator_account_id)"
     echo "  -a account      Account (default: $account)"
     echo "  -u user         User (default: $user)"
 }
@@ -130,7 +134,7 @@ next() {
 
 #  3. Parse command line options
 
-while getopts isfvmO:C:S:E:a:u:? arg; do
+while getopts isfvmoO:C:S:E:A:a:u:? arg; do
     case $arg in
     i)  interactive=1;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
@@ -141,6 +145,7 @@ while getopts isfvmO:C:S:E:a:u:? arg; do
     C)  company="$OPTARG";;
     S)  system="$OPTARG";;
     E)  environment="$OPTARG";;
+    A)  administrator_account_id="$OPTARG";;
     a)  account="$OPTARG";;
     u)  user="$OPTARG";;
     ?)  usage
@@ -200,6 +205,12 @@ else
         echo "-E $environment invalid! Must be Identity"
         exit 21;;
     esac
+fi
+
+if [ -z $administrator_account_id ]; then
+    echo "-A administrator_account_id missing!"
+    echo "Could not automatically determine administrator_account_id, and it was not specified as a parameter"
+    exit 49
 fi
 
 s3_domain=s3.amazonaws.com
@@ -334,6 +345,7 @@ aws cloudformation create-stack --stack-name StandardRoles \\
                                 $template_parameter \\
                                 $stack_policy_parameter \\
                                 --parameters ParameterKey=StandardManagedPoliciesStackName,ParameterValue=StandardManagedPolicies \\
+                                             ParameterKey=AdministratorAccount,ParameterValue=$administrator_account_id \\
                                 --tags Key=Owner,Value=$owner \\
                                        Key=Company,Value=$company \\
                                        Key=System,Value=$system \\
diff --git a/utility/bin/utility-update-openvpnas-stack b/utility/bin/utility-update-openvpnas-stack
--- a/utility/bin/utility-update-openvpnas-stack
+++ b/utility/bin/utility-update-openvpnas-stack
@@ -29,6 +29,7 @@ environment=${ENVIRONMENT_NAME:-Production}
 environment_type=small  # By default, these should use small
 utility=${UTILITY_NAME:-OpenVPNAS}
 utility_domain=${UTILITY_DOMAIN:-vpn}
+utility_version=${UTILITY_VERSION:-2.5.0}
 utility_license=${UTILITY_LICENSE:-2}
 user_networks=${OPENVPN_USER_NETWORKS:-0.0.0.0/0,NONE,NONE,NONE,NONE,NONE,NONE,NONE}  # This should be global for the VPN to work
 administrator_networks=${OPENVPN_ADMINISTRATOR_NETWORKS:-NONE,NONE,NONE,NONE,NONE,NONE,NONE,NONE}
@@ -44,7 +45,7 @@ usage () {
     echo "Usage: ${BASH_SOURCE##*/} [[-i] | [-s | -f]] [-v] [-m] [-o]"
     echo "                  [-O owner] [-C company] [-S system]"
     echo "                  [-E environment] [-T type]"
-    echo "                  [-U utility] [-D domain] [-L license]"
+    echo "                  [-U utility] [-D domain] [-V version] [-L license]"
     echo "                  [-n networks] [-N networks]"
     echo "                  [-r region] [-a account] [-u user] [-k key]"
     echo "  -i              interactive"
@@ -60,6 +61,7 @@ usage () {
     echo "  -T type         Environment Type (default: $environment_type)"
     echo "  -U utility      Utility Name (default: $utility)"
     echo "  -D domain       Utility Domain (default: $utility_domain)"
+    echo "  -V version      Utility Version (default: $utility_version)"
     echo "  -L license      Utility License (default: $utility_license)"
     echo "  -n networks     User Networks (default: $user_networks)"
     echo "  -N networks     Administrator Networks (default: $administrator_networks)"
@@ -149,7 +151,7 @@ next() {
 
 #  3. Parse command line options
 
-while getopts isfvmoO:C:S:E:T:U:D:L:n:N:r:a:u:k:? arg; do
+while getopts isfvmoO:C:S:E:T:U:D:V:L:n:N:r:a:u:k:? arg; do
     case $arg in
     i)  interactive=1;;
     s)  ((speed < speed_max)) && ((speed=speed+25));;
@@ -164,6 +166,7 @@ while getopts isfvmoO:C:S:E:T:U:D:L:n:N:r:a:u:k:? arg; do
     T)  environment_type="$OPTARG";;
     U)  utility="$OPTARG";;
     D)  utility_domain="$OPTARG";;
+    V)  utility_version="$OPTARG";;
     L)  utility_license="$OPTARG";;
     n)  user_networks="$OPTARG";;
     N)  administrator_networks="$OPTARG";;
@@ -246,10 +249,10 @@ if [ -z $environment_type ]; then
     exit 22
 else
     case $environment_type in
-      micro|small|medium|large|xlarge)
+      nano|micro|small|medium|large|xlarge)
         ;;
       *)
-        echo "-T $environment_type invalid! Must be micro, small, medium, large or xlarge"
+        echo "-T $environment_type invalid! Must be nano, micro, small, medium, large or xlarge"
         exit 23;;
     esac
 fi
@@ -274,17 +277,23 @@ if [ -z $utility_domain ]; then
     exit 32
 fi
 
+if [ -z $utility_version ]; then
+    echo "-V version missing!"
+    echo "Could not automatically determine version, and it was not specified as a parameter"
+    exit 34
+fi
+
 if [ -z $utility_license ]; then
     echo "-L license missing!"
     echo "Could not automatically determine license, and it was not specified as a parameter"
-    exit 34
+    exit 36
 else
     case $utility_license in
-      2|10|25|50)
+      2|10|25|50|100)
         openvpnas_license=OpenVPNAS$utility_license;;
       *)
-        echo "-L $utility_license invalid! Must be 2, 10, 25 or 50."
-        exit 35;;
+        echo "-L $utility_license invalid! Must be 2, 10, 25, 50 or 100."
+        exit 37;;
     esac
 fi
 
@@ -349,6 +358,16 @@ if ! aws cloudformation describe-stacks --stack-name $environment-$utility \
     echo
     echo "Unable to update - $environment-$utility Stack does not exist!"
     exit 98
+else
+    echo -n "."
+fi
+
+activedirectory_stack=$environment-ActiveDirectory
+if ! aws cloudformation describe-stacks --stack-name $activedirectory_stack \
+                                        --profile $profile --region $region --output text &> /dev/null; then
+    echo
+    echo "Stack optional dependency missing - $environment-ActiveDirectory Stack does not exist!"
+    activedirectory_stack=""
 else
     echo -n "."
 fi
@@ -455,7 +474,7 @@ aws cloudformation update-stack --stack-name $environment-$utility \\
                                 --parameters ParameterKey=ActiveDirectoryStackName,ParameterValue=$activedirectory_stack \\
                                              ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
                                              ParameterKey=CustomIdentifierFunctionsStackName,ParameterValue=CustomIdentifierFunctions \\
-                                             ParameterKey=StandardAMIFunctionsStackName,ParameterValue=StandardAMIFunctions \\
+                                             ParameterKey=CustomAMIFunctionsStackName,ParameterValue=CustomAMIFunctions \\
                                              ParameterKey=StandardBucketsStackName,ParameterValue=StandardBuckets \\
                                              ParameterKey=StandardTopicsStackName,ParameterValue=StandardTopics \\
                                              ParameterKey=KeyName,ParameterValue=$key \\
@@ -464,6 +483,7 @@ aws cloudformation update-stack --stack-name $environment-$utility \\
                                              ParameterKey=EnvironmentType,ParameterValue=$environment_type \\
                                              ParameterKey=UtilityName,ParameterValue=$utility \\
                                              ParameterKey=UtilityDomain,ParameterValue=$utility_domain \\
+                                             ParameterKey=UtilityVersion,ParameterValue=$utility_version \\
                                              ParameterKey=UtilityLicense,ParameterValue=$openvpnas_license \\
                                              ParameterKey=UserNetworks,ParameterValue=\"$user_networks\" \\
                                              ParameterKey=AdministratorNetworks,ParameterValue=\"$administrator_networks\" \\
