small fixes for consistency to get this running again

diff --git a/utility/bin/utility-create-openvpnas-stack b/utility/bin/utility-create-openvpnas-stack
--- a/utility/bin/utility-create-openvpnas-stack
+++ b/utility/bin/utility-create-openvpnas-stack
@@ -243,10 +243,10 @@ if [ -z $environment_type ]; then
     exit 22
 else
     case $environment_type in
-      micro|small|medium|large|xlarge)
+      nano|micro|small|medium|large|xlarge)
         ;;
       *)
-        echo "-T $environment_type invalid! Must be micro, small, medium, large or xlarge"
+        echo "-T $environment_type invalid! Must be nano, micro, small, medium, large or xlarge"
         exit 23;;
     esac
 fi
@@ -359,10 +359,10 @@ else
     echo -n "."
 fi
 
-if ! aws cloudformation describe-stacks --stack-name StandardAMIFunctions \
+if ! aws cloudformation describe-stacks --stack-name CustomAMIFunctions \
                                         --profile $profile --region $region --output text &> /dev/null; then
     echo
-    echo "Stack dependency missing - StandardAMIFunctions Stack does not exist!"
+    echo "Stack dependency missing - CustomAMIFunctions Stack does not exist!"
     exit 62
 else
     echo -n "."
@@ -495,7 +495,7 @@ aws cloudformation create-stack --stack-name $environment-$utility \\
                                 --parameters ParameterKey=ActiveDirectoryStackName,ParameterValue=$activedirectory_stack \\
                                              ParameterKey=VPCStackName,ParameterValue=$environment-VPC \\
                                              ParameterKey=CustomIdentifierFunctionsStackName,ParameterValue=CustomIdentifierFunctions \\
-                                             ParameterKey=StandardAMIFunctionsStackName,ParameterValue=StandardAMIFunctions \\
+                                             ParameterKey=CustomAMIFunctionsStackName,ParameterValue=CustomAMIFunctions \\
                                              ParameterKey=StandardBucketsStackName,ParameterValue=StandardBuckets \\
                                              ParameterKey=StandardTopicsStackName,ParameterValue=StandardTopics \\
                                              ParameterKey=KeyName,ParameterValue=$key \\
